name: 'TOAST UI Example Page 404 Checker(browserStack)'
description: 'TOAST UI Example Page 404 Checker'
inputs:
  urls:
    description: 'urls'
    required: true
  global-error-log-variable:
    description: 'error log array variable name(ex: errorLogs)'
    required: true
    default: false
  browsers:
    description: 'browser list'
    required: true
    default: 'ie10, ie11, safari, edge, chrome, firefox'
  filepath:
    description: 'file path(tuidoc.config.js file path)'
    required: true
    default: 'examples'
outputs:
  result:
    description: 'test result'
runs:
  using: 'node12'
  main: 'dist/index.js'
